### ISSUE TITLE
MOCHA ERR: TypeScript/JavaScript Challenges

### ISSUE THREAD

**Issue by FernandoBoza** [TSiege/Tech-Interview-Cheat-Sheet#6]
Might be a noob issue, but i'm trying to run the Typscript test and after installing all modules, i npm run test and get back this err, so i tried googling it and found this [stackoverflow](https://stackoverflow.com/questions/60283197/mocha-opts-deprecated-how-to-migrate-to-package-json) question but no answer.

Has anyone figured this out?

`
(node:2100) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
`

**Right After it's as Follows in my Terminal**

`Challenges
    Selection Sort
      swap
        1) swaps position of two items in an array given their indices

  0 passing (19ms)
  1 failing

  1) Challenges
       Selection Sort
         swap
           swaps position of two items in an array given their indices:

      AssertionError: expected [ 4, 3, 2, 1 ] to deeply equal [ 1, 3, 2, 4 ]
      + expected - actual

       [
      -  4
      +  1
         3
         2
      -  1
      +  4
       ]
      
      at Context.<anonymous> (challenges/challenges.test.ts:13:16)
      at processImmediate (internal/timers.js:439:21)

npm ERR! Test failed.  See above for more details.`

**Comment by TSiege** [comment]
@FernandoBoza That's a normal error from the tests. It's indicating that the order of the elements in the array from that function returns is incorrect. The warning it spits out is about Mocha deprecating a feature I'm using. I'll make an issue for the project. Good luck with your learnings!
